server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh
          uri: lb://cloud-payment-service #配置后提供服务的路由地址
          predicates:
            - Path=/payment/get/**
            #- After=2020-12-19T13:14:22.642+08:00[Asia/Shanghai]

        - id: payment_routh2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
            #- After=2020-12-19T12:11:22.642+08:00[Asia/Shanghai]
            #- Between=2020-12-19T13:14:22.642+08:00[Asia/Shanghai],2020-12-22T14:14:22.642+08:00[Asia/Shanghai]
            #- Cookie=username,jianghaowen
            #- Header=X-Request-Id,\d+
          

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    hostname: cloud-gateway-service
